"""add vndb_id column in tags model

Revision ID: f39b7c0844c5
Revises: 83f32438a9f3
Create Date: 2025-04-10 15:27:41.127229

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f39b7c0844c5"
down_revision: Union[str, None] = "83f32438a9f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
