name: Run Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "AWS Access Key, Secret, and Region are set for the session"
          echo "AWS_SECRET_ACCESS_KEY starts with: ${AWS_SECRET_ACCESS_KEY:0:4}..."
          echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}"
          echo "DATABASE_URL=sqlite:///:memory:" >> .env

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV


      - name: Validate linter
        run: flake8 backend/app

      - name: Run tests
        run: |
          pytest
